<a href="https://colab.research.google.com/github/Salina2060/Artificial-Intelligence-and-Machine-Learning/blob/main/2407800_Salina_Pudasaini_Worksheet_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Salina Pudasaini**

**University Id: 2407800**

**4.1 Exercise on Functions**

**Task- 1**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. **Functions:** Define at least one function to perform the conversion.
2. **Error Handling:** Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. **User Input:** Prompt the user to select the conversion type and input the value.
4. **Docstrings:** Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1.** Length:**– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
2. **Weight:**– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
3. **Volume:**– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units():
    """
    Prompts user for a conversion type and value, then performs the conversion.
    Supports: Length (m/ft), Weight (kg/lbs), Volume (L/gal).
    """
    print("Choose Conversion Type: 1. Length  2. Weight  3. Volume")

    try:
        choice = input("Enter choice (1, 2, or 3): ")

        if choice == '1':
            val = float(input("Enter length in meters to convert to feet: "))
            print(f"{val} meters is {val * 3.28084:.2f} feet.")
        elif choice == '2':
            val = float(input("Enter weight in kg to convert to lbs: "))
            print(f"{val} kg is {val * 2.20462:.2f} lbs.")
        elif choice == '3':
            val = float(input("Enter volume in Liters to convert to Gallons: "))
            print(f"{val} L is {val * 0.264172:.2f} gallons.")
        else:
            print("Invalid conversion type selected.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")

convert_units()

Choose Conversion Type: 1. Length  2. Weight  3. Volume
Enter choice (1, 2, or 3): 2
Enter weight in kg to convert to lbs: 45
45.0 kg is 99.21 lbs.


**Task-2**

Create a Python program that performs various mathematical operations on a list of numbers.

**• The Program should:**
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

**• Requirements:**
1. **Functions:** Define at least one function for each operation (sum, average, maximum, mini
mum).
2. **Error Handling:** Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. **User Input:** Prompt the user to select the operation and input the list of numbers.
4. **Docstrings:** Include a docstring in each function to describe its purpose, parameters, and
return value

In [ ]:
def find_sum(numbers):
    """
    Calculate the sum of numbers in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of numbers in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Maximum number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Minimum number in the list.
    """
    return min(numbers)


def main():
    try:
        print("Choose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter your choice (1-4): ")

        user_input = input("Enter numbers separated by spaces: ")

        numbers = [float(num) for num in user_input.split()]

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == "1":
            print("Sum:", find_sum(numbers))
        elif choice == "2":
            print("Average:", find_average(numbers))
        elif choice == "3":
            print("Maximum:", find_max(numbers))
        elif choice == "4":
            print("Minimum:", find_min(numbers))
        else:
            print("Invalid operation choice.")

    except ValueError:
        print("Error: Please enter valid numeric values.")


if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 6 5 1
Sum: 12.0


**4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**
Write a Python function that extracts every other element from a list, starting from the first element.

**• Requirements:**– Define a function extract
every
other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element starting from the first.
    Parameter: lst (list)
    Returns: A new list with elements at indices 0, 2, 4...
    """
    # [::2] means start at the beginning, go to the end,
    # and take a 'step' of 2.
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


**2. Slice a Sublist:**
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

**• Requirements:**– Define a function get
sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from index start to end (inclusive).
    """
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


**3. Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing.

**• Requirements:**

– Define a function reverse
slicing.
list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1]

In [ ]:
def reverse_list(lst):
    """
    Returns the reversed list using slicing.
    """
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

**• Requirements:**– Defineafunction remove
first
last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements from the list.
    """
    return lst[1:-1]


print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


**5. Get the First n Elements:**
Write a Python function that extracts the first n elements from a list.
**• Requirements:**
– Define a function get
first
n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements of the list.
    """
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


**6. Extract Elements from the End:**
Write a Python function that extracts the last n elements of a list using slicing.

**• Requirements:**
– Define a function get
last
n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5]

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements of the list.
    """
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


**7. Extract Elements in Reverse Order:**
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

**• Requirements:**– Define a function reverse
skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]

In [ ]:
def reverse_skip(lst):
    """
    Returns every second element starting from the second-to-last
    element moving backward.
    """
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


**4.3  Exercise on Nested List**

**1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

**• Requirements:**
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5]

In [ ]:
def flatten(lst):
    """
    Flattens a list of lists into a single list.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

flatten([[1, 2], [3, 4], [5]])

[1, 2, 3, 4, 5]

**2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.

**• Requirements:**
– Define a function access
nested
element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6

In [ ]:
def access_nested_element(lst, indices):
    """
    Returns the element at specific coordinates [row, col].
    """
    row = indices[0]
    col = indices[1]
    return lst[row][col]

access_nested_element([[1, 2, 3], [4, 5, 6]], [1, 2])

6

**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

**• Requirements**:
– Define a function sum
nested(lst) that takes a nested list lst and returns the sum of all
the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21

In [ ]:
def sum_nested(lst):
    total = 0
    # 'To-Do List' starts with the main list
    todo_list = [lst]

    while todo_list:
        #taking the last item out of our 'To-Do List'
        current_item = todo_list.pop()

        for item in current_item:
            if isinstance(item, list):
                #if we find another list, add it to the 'To-Do List'
                todo_list.append(item)
            else:
                # If it's a number, add it to the total
                total += item

    return total


print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


**4. Remove Specific Element from a Nested List:**
Write a Python function that removes all occurrences of a specific element from a nested list.

**• Requirements:**
– Define a function remove
element(lst, elem) that removes elem from lst and returns the
modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
be [[1], [3], [4, 5]]

In [ ]:
def remove_element(lst, elem):
    for sublist in lst:
        # While the element is still in this sub-list, keep removing it
        while elem in sublist:
            sublist.remove(elem)
    return lst

remove_element([[1, 2], [3, 2], [4, 5]], 2)

[[1], [3], [4, 5]]

**5. Find the Maximum Element in a Nested List:**
Write a Python function that finds the maximum element in a nested list (regardless of depth).

**• Requirements:**
– Define a function find
element.
max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


def find_max(lst):
    flat = deep_flatten(lst)
    return max(flat)


print(find_max([[1, 2], [3, [4, 5]], 6]))

6


**6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.

**• Requirements:**– Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
be 3

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    todo_list = [lst]

    while todo_list:
        current_item = todo_list.pop()

        for item in current_item:
            if isinstance(item, list):
                # If it's a list, save it for later
                todo_list.append(item)
            elif item == elem:
                # If it matches our number, count it
                count += 1

    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


**7. Flatten a List of Lists of Lists:**
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

**• Requirements:**– Define a function deep
flatten(lst) that takes a deeply nested list lst and returns a single
f
lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            # use .extend to add items from the inner list to our result
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

deep_flatten([[[1, 2]], [[3, 4]]])

[1, 2, 3, 4]

**8. Nested List Average:**
Write a Python function that calculates the average of all elements in a nested list.

**• Requirements:**
– Define a function average
of all the elements.
nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    # Flatten the list so we have all numbers in one place
    flat_list = deep_flatten(lst)

    # Calculate sum / count
    if len(flat_list) == 0:
        return 0

    return sum(flat_list) / len(flat_list)

average_nested([[1, 2], [3, 4], [5, 6]])

3.5

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem- 1: Array Creation:**
Complete the following Tasks:


In [ ]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
empty_array = np.empty((2, 2))
print(empty_array)

[[3.57862682e-315 0.00000000e+000]
 [6.78352699e-310 5.77904633e-317]]


2. Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
full_array = np.full((3, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
# Given an existing array
existing_arr = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a new zeros array with the same shape
zeros_like_arr = np.zeros_like(existing_arr)
print(zeros_like_arr)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_arr = np.ones_like(existing_arr)
print(ones_like_arr)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
# Existing list
new_list = [1, 2, 3, 4]

#Converting to a numpy array
numpy_arr = np.array(new_list)
print(numpy_arr)

[1 2 3 4]


**Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr_range = np.arange(10, 50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_arr = np.random.random(30)

mean_val = random_arr.mean()
print("Mean:", mean_val)

Mean: 0.514162345037084


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
big_random = np.random.random((10, 10))

print("Minimum:", big_random.min())
print("Maximum:", big_random.max())

Minimum: 0.015700801079206905
Maximum: 0.9818222942272365


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_arr = np.zeros(10)

# Replacing 5th element (index 4) with 1
zero_arr[4] = 1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])

#Reversed using slicing
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
# Create a 5x5 array of ones
border_arr = np.ones((5, 5))

# Use slicing to set interior (excluding first and last row/column) to 0
border_arr[1:-1, 1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
#Create 8x8 array of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill with 1s in a checkerboard pattern
# Put 1s in rows 1,3,5,7 and columns 0,2,4,6
# This fills alternate squares
checkerboard[1::2, ::2] = 1

# Put 1s in rows 0,2,4,6 and columns 1,3,5,7
# This fills the remaining alternate squares
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem- 3: Array Operations:**


**For the following arrays: x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:**

In [ ]:
# Defining the given arrays
x = np.array([[1,2],[3,5]]) ;
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]);
w = np.array([11,12]);

1. Add the two array.

In [ ]:
sum_xy = x + y
print("Addition of x and y:\n", sum_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array

In [ ]:
diff_xy = x - y
print("Subtraction of x and y:\n", diff_xy)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
mul_x = x * 3
print("Multiplication of x by 3:\n", mul_x)

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
squared_x = x ** 2
print("Square of elements in x:\n", squared_x)

Square of elements in x:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
# Dot product between v and w
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

# Dot product between x and v
dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

# Dot product between x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
row_concat_xy = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", row_concat_xy)

col_concat_vw = np.concatenate((v, w), axis=0)
print("Concatenate v and w along column:\n", col_concat_vw)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [ 9 10 11 12]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# x = np.array([[1,2],[3,5]])
# v = np.array([9,10])

# #trying to concatenate x and v
# result = np.concatenate((x, v))
# print(result)

Here, The error occurs because of a dimension mismatch. Array x is a 2D array with shape (2, 2), while array v is a 1D array with shape (2,). NumPy's concatenate function requires all input arrays to have the same number of dimensions. To fix this, we should reshape v into a 2D array before concatenating.

**Problem- 4: Matrix Operations:**


**• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);**

In [ ]:
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]


Prove following with Numpy:

**1. Prove A.(A)^−1 = I.**

In [ ]:
# Given matrix
A = np.array([[3,4],[7,8]])

# Finding inverse of A
A_inv = np.linalg.inv(A)

# Multiply A and its inverse
result = np.dot(A, A_inv)

print(result)

#Checking if result is identity matrix
print("Is it the Identity Matrix?", np.allclose(result, np.eye(2)))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is it the Identity Matrix? True


**2. Prove AB ≠ BA.**

In [ ]:
#calculate A * B
AB = np.dot(A, B)

#calculate B * A
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

# Checking if they are equal
print("Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


**3. Prove (AB)^T = (B^T)(A^T).**

In [ ]:
#LHS: Transpose of (AB)
LHS = (np.dot(A, B)).T

#RHS: (B transpose) * (A transpose)
RHS = np.dot(B.T, A.T)

print("LHS (AB)^T:\n", LHS)
print("RHS (B^T)(A^T):\n", RHS)

#Check if both sides are equal
print("Is (AB)^T equal to (B^T)(A^T)?", np.array_equal(LHS, RHS))

LHS (AB)^T:
 [[23 51]
 [13 29]]
RHS (B^T)(A^T):
 [[23 51]
 [13 29]]
Is (AB)^T equal to (B^T)(A^T)? True


**• Solve the following system of Linear equation using Inverse Methods.**

2x −3y+z =−1

x −y+2z =−3

3x +y−z =9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
#coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

#constant matrix B
B = np.array([-1, -3, 9])

# Solve using the inverse method
X = np.dot(np.linalg.inv(A), B)

print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


 Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [ ]:
import numpy as np

# Use linalg module to find inverse
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

#find inverse using linalg.inv
A_inv = np.linalg.inv(A)

# multiply A_inv with B
X = np.dot(A_inv, B)

print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation

In [ ]:
import numpy as np
import time

#List the size for 1D operations
size = 1000000

In [ ]:
#Element-wise Addition
# Python Lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = []
for i in range(size):
    result_list.append(list1[i] + list2[i])
print(f"Python List Addition: {time.time() - start:.5f} sec")

# NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result_arr = arr1 + arr2
print(f"NumPy Array Addition: {time.time() - start:.5f} sec")

Python List Addition: 0.50640 sec
NumPy Array Addition: 0.00215 sec


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation

In [ ]:
#Element-wise Multiplication ---
# Python Lists
start = time.time()
result_list = []
for i in range(size):
    result_list.append(list1[i] * list2[i])
print(f"Python List Multiplication: {time.time() - start:.5f} sec")

# NumPy Arrays
start = time.time()
result_arr = arr1 * arr2
print(f"NumPy Array Multiplication: {time.time() - start:.5f} sec")

Python List Multiplication: 0.18493 sec
NumPy Array Multiplication: 0.00480 sec


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#Python Lists
start = time.time()
dot_product = 0
for i in range(size):
    dot_product += list1[i] * list2[i]
print(f"Python List Dot Product: {time.time() - start:.5f} sec")

# NumPy Arrays
start = time.time()
dot_product_arr = np.dot(arr1, arr2)
print(f"NumPy Array Dot Product: {time.time() - start:.5f} sec")

Python List Dot Product: 0.21760 sec
NumPy Array Dot Product: 0.00188 sec


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

size_mat = 1000

# using NumPy Arrays
#creating 1000x1000 matrices filled with ones
mat_a_np = np.ones((size_mat, size_mat))
mat_b_np = np.ones((size_mat, size_mat))

start_np = time.time()
#standard matrix multiplication in NumPy
res_np = np.dot(mat_a_np, mat_b_np)
end_np = time.time()

print(f"NumPy Matrix Multiplication (Size 1000): {end_np - start_np:.5f} sec")


#using Python Lists
#Creating 1000x1000 lists filled with ones
list_a = [[1.0] * size_mat for _ in range(size_mat)]
list_b = [[1.0] * size_mat for _ in range(size_mat)]
#initialising the result list with zeros
res_list = [[0.0] * size_mat for _ in range(size_mat)]

start_list = time.time()
# Using 3 nested loops for Matrix Multiplication
for i in range(size_mat):
    for j in range(size_mat):
        for k in range(size_mat):
            res_list[i][j] += list_a[i][k] * list_b[k][j]
end_list = time.time()

print(f"Python List Matrix Multiplication (Size 1000): {end_list - start_list:.5f} sec")

NumPy Matrix Multiplication (Size 1000): 0.09379 sec
Python List Matrix Multiplication (Size 1000): 310.14639 sec
